### ISSUE TITLE
Update current version info and details for `vegan`

### ISSUE THREAD

**Issue by naupaka** [naupaka/esa_intro_vegan_2015#2]
In 01-intro-basics slides - e.g. `vegan` is not at 3.2.0, right?

**Comment by gavinsimpson** [comment]
Fixed with 57d5cb342363572c03172b2aff07d4dc9ab1686d

**Comment by gavinsimpson** [comment]
Right: problems associated with making changes just before a session...

Vegan is 2.3-0
